name: 'Smoke test'
inputs:
  template:
    description: 'Template to test'
    required: true

runs:
  using: composite
  steps:
    - name: Checkout main
      id: checkout_release
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

    - name: Build template
      id: build_template
      shell: bash
      run: ${{ github.action_path }}/build.sh nix templates/test/${{ inputs.template }}

    - name: Test template
      id: test_template
      shell: bash
      run: ${{ github.action_path }}/test.sh nix templates/test/${{ inputs.template }}