name: latest-build-flake
on:
  workflow_dispatch:
  pull_request:
    branches:
      - develop
  push:
    tags:
      - v*
    branches:
      - develop
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build test image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile-flake
          build-args: |
            MAIN_NIX_CHANNEL=https://nixos.org/channels/nixpkgs-unstable
            HOME_MANAGER_CHANNEL=https://github.com/nix-community/home-manager/archive/master.tar.gz
          push: false
          load: true
          tags: ghcr.io/lucernae/devcontainer-nix:flake---latest
          cache-from: |
            type=gha,scope=test
            type=gha,scope=prod
          cache-to: type=gha,scope=test

      - name: Run docker-compose services
        run: |
          cp docker-compose.flake.yml docker-compose.override.yml
          make up

      - name: Run Coverage test
        run: |
          cat << EOF | docker-compose exec -T devcontainer bash
          node --version
          EOF

  docker-builder:
    # Only push if PR happens in the same repo
    if: github.event.pull_request.base.repo.url == github.event.pull_request.head.repo.url
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io

          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_PASSWORD }}

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/lucernae/devcontainer-nix
          flavor: |
            latest=false
            prefix=flake---
          tags: |
            type=raw,value=stable,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
            type=raw,value=flake,prefix=,enable=${{ github.ref == format('refs/heads/{0}', 'develop') }}
            type=ref,event=branch
            type=ref,event=pr
            type=ref,event=tag
            type=semver,pattern=v{{version}}
            type=semver,pattern=v{{major}}
            type=semver,pattern=v{{major}}.{{minor}}
            type=semver,pattern=v{{major}}.{{minor}}.{{patch}}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile-flake
          build-args: |
            MAIN_NIX_CHANNEL=https://nixos.org/channels/nixpkgs-unstable
            HOME_MANAGER_CHANNEL=https://github.com/nix-community/home-manager/archive/master.tar.gz
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          cache-from: |
            type=gha,scope=test
            type=gha,scope=prod
          cache-to: type=gha,scope=prod

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}